name: interpreter

version: 0.1.0.0

ghc-options: -Wall -O2

dependencies:
  - base
  - containers
  - ansi-terminal
  - rainbow
  - process
  - split
  - mtl
  - transformers
  - pipes
  - text
  - yaml
  - either
  - strict
  - random
  - protolude

library:
  source-dirs: src/

tests:
  interpreter-test:
    main: Spec.hs
    source-dirs: test/ 
    dependencies:
      - interpreter
      - hspec